prompt PL/SQL Developer Export Tables for user JPEREZ@LOCALHOST:1521/XE
prompt Created by jp570 on martes, 20 de mayo de 2025
set feedback off
set define off

prompt Dropping MUSEUMS...
drop table MUSEUMS cascade constraints;
prompt Dropping ROOMS...
drop table ROOMS cascade constraints;
prompt Dropping COLLECTIONS...
drop table COLLECTIONS cascade constraints;
prompt Dropping PAYMENT_METHOD...
drop table PAYMENT_METHOD cascade constraints;
prompt Dropping ENTRIES...
drop table ENTRIES cascade constraints;
prompt Dropping PRICES...
drop table PRICES cascade constraints;
prompt Dropping RATINGS...
drop table RATINGS cascade constraints;
prompt Dropping SPECIES...
drop table SPECIES cascade constraints;
prompt Dropping THEMATICS...
drop table THEMATICS cascade constraints;
prompt Creating MUSEUMS...
create table MUSEUMS
(
  id          NUMBER generated by default as identity,
  name        VARCHAR2(100) not null,
  museum_type VARCHAR2(50) not null,
  location    VARCHAR2(150),
  foundation  DATE,
  director    VARCHAR2(100),
  website     VARCHAR2(200)
)
tablespace USERS
  pctfree 10
  initrans 1
  maxtrans 255;
alter table MUSEUMS
  add primary key (ID)
  using index
  tablespace USERS
  pctfree 10
  initrans 2
  maxtrans 255;

prompt Creating ROOMS...
create table ROOMS
(
  id          NUMBER generated by default as identity,
  name        VARCHAR2(100) not null,
  description VARCHAR2(200),
  museum_id   NUMBER not null
)
tablespace USERS
  pctfree 10
  initrans 1
  maxtrans 255;
alter table ROOMS
  add primary key (ID)
  using index
  tablespace USERS
  pctfree 10
  initrans 2
  maxtrans 255;
alter table ROOMS
  add foreign key (MUSEUM_ID)
  references MUSEUMS (ID);

prompt Creating COLLECTIONS...
create table COLLECTIONS
(
  id          NUMBER generated by default as identity,
  name        VARCHAR2(100) not null,
  description VARCHAR2(500),
  century     VARCHAR2(20) not null,
  room_id     NUMBER not null
)
tablespace USERS
  pctfree 10
  initrans 1
  maxtrans 255;
alter table COLLECTIONS
  add primary key (ID)
  using index
  tablespace USERS
  pctfree 10
  initrans 2
  maxtrans 255;
alter table COLLECTIONS
  add foreign key (ROOM_ID)
  references ROOMS (ID) on delete cascade;

prompt Creating PAYMENT_METHOD...
create table PAYMENT_METHOD
(
  id         NUMBER generated by default as identity,
  type       VARCHAR2(50) not null,
  commission NUMBER(5,2) not null
)
tablespace USERS
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
alter table PAYMENT_METHOD
  add primary key (ID)
  using index
  tablespace USERS
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
alter table PAYMENT_METHOD
  add unique (TYPE)
  using index
  tablespace USERS
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
alter table PAYMENT_METHOD
  add check (commission >= 0 AND commission <= 100);

prompt Creating ENTRIES...
create table ENTRIES
(
  id                NUMBER generated by default as identity,
  room_id           NUMBER not null,
  payment_method_id NUMBER not null,
  visit_date        DATE not null,
  purchase_date     DATE default SYSDATE not null,
  price             NUMBER(7,2) not null,
  commission_amount NUMBER(7,2) not null,
  qr_code           VARCHAR2(255) not null
)
tablespace USERS
  pctfree 10
  initrans 1
  maxtrans 255;
alter table ENTRIES
  add primary key (ID)
  using index
  tablespace USERS
  pctfree 10
  initrans 2
  maxtrans 255;
alter table ENTRIES
  add unique (QR_CODE)
  using index
  tablespace USERS
  pctfree 10
  initrans 2
  maxtrans 255;
alter table ENTRIES
  add foreign key (ROOM_ID)
  references ROOMS (ID) on delete cascade;
alter table ENTRIES
  add foreign key (PAYMENT_METHOD_ID)
  references PAYMENT_METHOD (ID);
alter table ENTRIES
  add check (price >= 0);
alter table ENTRIES
  add check (commission_amount >= 0);

prompt Creating PRICES...
create table PRICES
(
  id           NUMBER generated by default as identity,
  normal_price NUMBER(7,2) not null,
  sunday_price NUMBER(7,2) not null,
  room_id      NUMBER not null
)
tablespace USERS
  pctfree 10
  initrans 1
  maxtrans 255;
alter table PRICES
  add primary key (ID)
  using index
  tablespace USERS
  pctfree 10
  initrans 2
  maxtrans 255;
alter table PRICES
  add foreign key (ROOM_ID)
  references ROOMS (ID) on delete cascade;
alter table PRICES
  add check (normal_price >= 0);
alter table PRICES
  add check (sunday_price >= 0);

prompt Creating RATINGS...
create table RATINGS
(
  id          NUMBER generated by default as identity,
  room_id     NUMBER not null,
  rating      NUMBER(1),
  observation VARCHAR2(300),
  rating_date DATE default SYSDATE
)
tablespace USERS
  pctfree 10
  initrans 1
  maxtrans 255;
alter table RATINGS
  add primary key (ID)
  using index
  tablespace USERS
  pctfree 10
  initrans 2
  maxtrans 255;
alter table RATINGS
  add foreign key (ROOM_ID)
  references ROOMS (ID) on delete cascade;
alter table RATINGS
  add check (rating BETWEEN 1 AND 5);

prompt Creating SPECIES...
create table SPECIES
(
  id              NUMBER generated by default as identity,
  scientific_name VARCHAR2(100),
  common_name     VARCHAR2(50),
  extintion_date  DATE,
  period          VARCHAR2(20),
  weight          NUMBER(6,2),
  features        VARCHAR2(500),
  collection_id   NUMBER not null
)
tablespace USERS
  pctfree 10
  initrans 1
  maxtrans 255;
alter table SPECIES
  add primary key (ID)
  using index
  tablespace USERS
  pctfree 10
  initrans 2
  maxtrans 255;
alter table SPECIES
  add foreign key (COLLECTION_ID)
  references COLLECTIONS (ID);
alter table SPECIES
  add check (weight >= 0);

prompt Creating THEMATICS...
create table THEMATICS
(
  id       NUMBER generated by default as identity,
  name     VARCHAR2(100) not null,
  features VARCHAR2(500),
  period   VARCHAR2(20),
  room_id  NUMBER not null
)
tablespace USERS
  pctfree 10
  initrans 1
  maxtrans 255;
alter table THEMATICS
  add primary key (ID)
  using index
  tablespace USERS
  pctfree 10
  initrans 2
  maxtrans 255;
alter table THEMATICS
  add foreign key (ROOM_ID)
  references ROOMS (ID) on delete cascade;

prompt Disabling triggers for MUSEUMS...
alter table MUSEUMS disable all triggers;
prompt Disabling triggers for ROOMS...
alter table ROOMS disable all triggers;
prompt Disabling triggers for COLLECTIONS...
alter table COLLECTIONS disable all triggers;
prompt Disabling triggers for PAYMENT_METHOD...
alter table PAYMENT_METHOD disable all triggers;
prompt Disabling triggers for ENTRIES...
alter table ENTRIES disable all triggers;
prompt Disabling triggers for PRICES...
alter table PRICES disable all triggers;
prompt Disabling triggers for RATINGS...
alter table RATINGS disable all triggers;
prompt Disabling triggers for SPECIES...
alter table SPECIES disable all triggers;
prompt Disabling triggers for THEMATICS...
alter table THEMATICS disable all triggers;
prompt Disabling foreign key constraints for ROOMS...
alter table ROOMS disable constraint SYS_C008328;
prompt Disabling foreign key constraints for COLLECTIONS...
alter table COLLECTIONS disable constraint SYS_C008334;
prompt Disabling foreign key constraints for ENTRIES...
alter table ENTRIES disable constraint SYS_C008360;
alter table ENTRIES disable constraint SYS_C008361;
prompt Disabling foreign key constraints for PRICES...
alter table PRICES disable constraint SYS_C008347;
prompt Disabling foreign key constraints for RATINGS...
alter table RATINGS disable constraint SYS_C008371;
prompt Disabling foreign key constraints for SPECIES...
alter table SPECIES disable constraint SYS_C008366;
prompt Disabling foreign key constraints for THEMATICS...
alter table THEMATICS disable constraint SYS_C008339;
prompt Loading MUSEUMS...
prompt Table is empty
prompt Loading ROOMS...
prompt Table is empty
prompt Loading COLLECTIONS...
prompt Table is empty
prompt Loading PAYMENT_METHOD...
insert into PAYMENT_METHOD (id, type, commission)
values (1, 'Visa', 3.25);
insert into PAYMENT_METHOD (id, type, commission)
values (2, 'Mastercard', 2.75);
insert into PAYMENT_METHOD (id, type, commission)
values (3, 'American Express', 4);
insert into PAYMENT_METHOD (id, type, commission)
values (4, 'Diners Club', 3.5);
insert into PAYMENT_METHOD (id, type, commission)
values (5, 'UnionPay', 3.1);
commit;
prompt 5 records loaded
prompt Loading ENTRIES...
prompt Table is empty
prompt Loading PRICES...
prompt Table is empty
prompt Loading RATINGS...
prompt Table is empty
prompt Loading SPECIES...
prompt Table is empty
prompt Loading THEMATICS...
prompt Table is empty
prompt Enabling foreign key constraints for ROOMS...
alter table ROOMS enable constraint SYS_C008328;
prompt Enabling foreign key constraints for COLLECTIONS...
alter table COLLECTIONS enable constraint SYS_C008334;
prompt Enabling foreign key constraints for ENTRIES...
alter table ENTRIES enable constraint SYS_C008360;
alter table ENTRIES enable constraint SYS_C008361;
prompt Enabling foreign key constraints for PRICES...
alter table PRICES enable constraint SYS_C008347;
prompt Enabling foreign key constraints for RATINGS...
alter table RATINGS enable constraint SYS_C008371;
prompt Enabling foreign key constraints for SPECIES...
alter table SPECIES enable constraint SYS_C008366;
prompt Enabling foreign key constraints for THEMATICS...
alter table THEMATICS enable constraint SYS_C008339;
prompt Enabling triggers for MUSEUMS...
alter table MUSEUMS enable all triggers;
prompt Enabling triggers for ROOMS...
alter table ROOMS enable all triggers;
prompt Enabling triggers for COLLECTIONS...
alter table COLLECTIONS enable all triggers;
prompt Enabling triggers for PAYMENT_METHOD...
alter table PAYMENT_METHOD enable all triggers;
prompt Enabling triggers for ENTRIES...
alter table ENTRIES enable all triggers;
prompt Enabling triggers for PRICES...
alter table PRICES enable all triggers;
prompt Enabling triggers for RATINGS...
alter table RATINGS enable all triggers;
prompt Enabling triggers for SPECIES...
alter table SPECIES enable all triggers;
prompt Enabling triggers for THEMATICS...
alter table THEMATICS enable all triggers;

set feedback on
set define on
prompt Done
