prompt PL/SQL Developer Export Tables for user JPEREZ@LOCALHOST:1521/XE
prompt Created by jp570 on martes, 17 de junio de 2025
set feedback off
set define off

prompt Dropping MUSEUMS...
drop table MUSEUMS cascade constraints;
prompt Dropping ROOMS...
drop table ROOMS cascade constraints;
prompt Dropping COLLECTIONS...
drop table COLLECTIONS cascade constraints;
prompt Dropping PAYMENT_METHODS...
drop table PAYMENT_METHODS cascade constraints;
prompt Dropping USERS...
drop table USERS cascade constraints;
prompt Dropping PURCHASES...
drop table PURCHASES cascade constraints;
prompt Dropping COMMISSIONS...
drop table COMMISSIONS cascade constraints;
prompt Dropping ENTRIES...
drop table ENTRIES cascade constraints;
prompt Dropping PRICES...
drop table PRICES cascade constraints;
prompt Dropping REVIEWS...
drop table REVIEWS cascade constraints;
prompt Dropping ROOM_IMAGES...
drop table ROOM_IMAGES cascade constraints;
prompt Dropping SPECIES...
drop table SPECIES cascade constraints;
prompt Dropping THEMES...
drop table THEMES cascade constraints;
prompt Dropping TRANSFERS...
drop table TRANSFERS cascade constraints;
prompt Creating MUSEUMS...
create table MUSEUMS
(
  id          NUMBER generated by default as identity,
  name        VARCHAR2(100) not null,
  museum_type VARCHAR2(50) not null,
  location    VARCHAR2(150),
  foundation  DATE,
  director    VARCHAR2(100),
  website     VARCHAR2(200)
)
tablespace MAHN_DATA
  pctfree 10
  initrans 1
  maxtrans 255;
alter table MUSEUMS
  add primary key (ID)
  using index
  tablespace MAHN_DATA
  pctfree 10
  initrans 2
  maxtrans 255;

prompt Creating ROOMS...
create table ROOMS
(
  id          NUMBER generated by default as identity,
  name        VARCHAR2(100) not null,
  description VARCHAR2(200),
  museum_id   NUMBER not null
)
tablespace MAHN_DATA
  pctfree 10
  initrans 1
  maxtrans 255;
alter table ROOMS
  add primary key (ID)
  using index
  tablespace MAHN_DATA
  pctfree 10
  initrans 2
  maxtrans 255;
alter table ROOMS
  add foreign key (MUSEUM_ID)
  references MUSEUMS (ID);

prompt Creating COLLECTIONS...
create table COLLECTIONS
(
  id          NUMBER generated by default as identity,
  name        VARCHAR2(100) not null,
  description VARCHAR2(500),
  century     VARCHAR2(20) not null,
  room_id     NUMBER not null
)
tablespace MAHN_DATA
  pctfree 10
  initrans 1
  maxtrans 255;
alter table COLLECTIONS
  add primary key (ID)
  using index
  tablespace MAHN_DATA
  pctfree 10
  initrans 2
  maxtrans 255;
alter table COLLECTIONS
  add foreign key (ROOM_ID)
  references ROOMS (ID) on delete cascade;

prompt Creating PAYMENT_METHODS...
create table PAYMENT_METHODS
(
  id                    NUMBER generated by default as identity,
  type                  VARCHAR2(50) not null,
  commission_percentage NUMBER(5,2) not null
)
tablespace MAHN_DATA
  pctfree 10
  initrans 1
  maxtrans 255;
alter table PAYMENT_METHODS
  add primary key (ID)
  using index
  tablespace MAHN_DATA
  pctfree 10
  initrans 2
  maxtrans 255;
alter table PAYMENT_METHODS
  add unique (TYPE)
  using index
  tablespace MAHN_DATA
  pctfree 10
  initrans 2
  maxtrans 255;
alter table PAYMENT_METHODS
  add check (commission_percentage >= 0 AND commission_percentage <= 100);

prompt Creating USERS...
create table USERS
(
  id                NUMBER generated by default as identity,
  name              VARCHAR2(100) not null,
  email             VARCHAR2(100) not null,
  password          VARCHAR2(100) not null,
  role              VARCHAR2(20) default 'client',
  phone             VARCHAR2(20),
  registration_date DATE default SYSDATE
)
tablespace MAHN_DATA
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
alter table USERS
  add primary key (ID)
  using index
  tablespace MAHN_DATA
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
alter table USERS
  add unique (EMAIL)
  using index
  tablespace MAHN_DATA
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );

prompt Creating PURCHASES...
create table PURCHASES
(
  id                NUMBER generated by default as identity,
  user_id           NUMBER not null,
  payment_method_id NUMBER not null,
  total_amount      NUMBER(7,2) not null,
  total_commission  NUMBER(7,2) not null,
  purchase_date     DATE default SYSDATE
)
tablespace MAHN_DATA
  pctfree 10
  initrans 1
  maxtrans 255;
alter table PURCHASES
  add primary key (ID)
  using index
  tablespace MAHN_DATA
  pctfree 10
  initrans 2
  maxtrans 255;
alter table PURCHASES
  add foreign key (USER_ID)
  references USERS (ID);
alter table PURCHASES
  add foreign key (PAYMENT_METHOD_ID)
  references PAYMENT_METHODS (ID);
alter table PURCHASES
  add check (total_amount >= 0);
alter table PURCHASES
  add check (total_commission >= 0);

prompt Creating COMMISSIONS...
create table COMMISSIONS
(
  id                NUMBER generated by default as identity,
  purchase_id       NUMBER not null,
  payment_method_id NUMBER not null,
  amount            NUMBER(7,2) not null,
  commission_date   DATE default SYSDATE
)
tablespace MAHN_DATA
  pctfree 10
  initrans 1
  maxtrans 255;
alter table COMMISSIONS
  add primary key (ID)
  using index
  tablespace MAHN_DATA
  pctfree 10
  initrans 2
  maxtrans 255;
alter table COMMISSIONS
  add foreign key (PURCHASE_ID)
  references PURCHASES (ID);
alter table COMMISSIONS
  add foreign key (PAYMENT_METHOD_ID)
  references PAYMENT_METHODS (ID);
alter table COMMISSIONS
  add check (amount >= 0);

prompt Creating ENTRIES...
create table ENTRIES
(
  id          NUMBER generated by default as identity,
  purchase_id NUMBER not null,
  room_id     NUMBER not null,
  visit_date  DATE not null,
  price       NUMBER(7,2) not null,
  qr_code     VARCHAR2(255) not null,
  status      VARCHAR2(20) default 'ACTIVE'
)
tablespace MAHN_DATA
  pctfree 10
  initrans 1
  maxtrans 255;
alter table ENTRIES
  add primary key (ID)
  using index
  tablespace MAHN_DATA
  pctfree 10
  initrans 2
  maxtrans 255;
alter table ENTRIES
  add unique (QR_CODE)
  using index
  tablespace MAHN_DATA
  pctfree 10
  initrans 2
  maxtrans 255;
alter table ENTRIES
  add foreign key (PURCHASE_ID)
  references PURCHASES (ID);
alter table ENTRIES
  add foreign key (ROOM_ID)
  references ROOMS (ID);
alter table ENTRIES
  add check (price >= 0);

prompt Creating PRICES...
create table PRICES
(
  id           NUMBER generated by default as identity,
  normal_price NUMBER(7,2) not null,
  sunday_price NUMBER(7,2) not null,
  room_id      NUMBER not null
)
tablespace MAHN_DATA
  pctfree 10
  initrans 1
  maxtrans 255;
alter table PRICES
  add primary key (ID)
  using index
  tablespace MAHN_DATA
  pctfree 10
  initrans 2
  maxtrans 255;
alter table PRICES
  add foreign key (ROOM_ID)
  references ROOMS (ID) on delete cascade;
alter table PRICES
  add check (normal_price >= 0);
alter table PRICES
  add check (sunday_price >= 0);

prompt Creating REVIEWS...
create table REVIEWS
(
  id           NUMBER generated by default as identity,
  user_id      NUMBER not null,
  room_id      NUMBER not null,
  rating       NUMBER(1),
  user_comment VARCHAR2(300),
  review_date  DATE default SYSDATE
)
tablespace MAHN_DATA
  pctfree 10
  initrans 1
  maxtrans 255;
alter table REVIEWS
  add primary key (ID)
  using index
  tablespace MAHN_DATA
  pctfree 10
  initrans 2
  maxtrans 255;
alter table REVIEWS
  add foreign key (USER_ID)
  references USERS (ID);
alter table REVIEWS
  add foreign key (ROOM_ID)
  references ROOMS (ID);
alter table REVIEWS
  add check (rating BETWEEN 1 AND 5);

prompt Creating ROOM_IMAGES...
create table ROOM_IMAGES
(
  id          NUMBER generated by default as identity,
  room_id     NUMBER not null,
  image_path  VARCHAR2(200) not null,
  description VARCHAR2(200)
)
tablespace MAHN_DATA
  pctfree 10
  initrans 1
  maxtrans 255;
alter table ROOM_IMAGES
  add primary key (ID)
  using index
  tablespace MAHN_DATA
  pctfree 10
  initrans 2
  maxtrans 255;
alter table ROOM_IMAGES
  add foreign key (ROOM_ID)
  references ROOMS (ID) on delete cascade;

prompt Creating SPECIES...
create table SPECIES
(
  id              NUMBER generated by default as identity,
  scientific_name VARCHAR2(100),
  common_name     VARCHAR2(50),
  extinction_date DATE,
  period          VARCHAR2(20),
  weight          NUMBER(6,2),
  features        VARCHAR2(500),
  collection_id   NUMBER not null
)
tablespace MAHN_DATA
  pctfree 10
  initrans 1
  maxtrans 255;
alter table SPECIES
  add primary key (ID)
  using index
  tablespace MAHN_DATA
  pctfree 10
  initrans 2
  maxtrans 255;
alter table SPECIES
  add foreign key (COLLECTION_ID)
  references COLLECTIONS (ID);
alter table SPECIES
  add check (weight >= 0);

prompt Creating THEMES...
create table THEMES
(
  id       NUMBER generated by default as identity,
  name     VARCHAR2(100) not null,
  features VARCHAR2(500),
  period   VARCHAR2(20),
  room_id  NUMBER not null
)
tablespace MAHN_DATA
  pctfree 10
  initrans 1
  maxtrans 255;
alter table THEMES
  add primary key (ID)
  using index
  tablespace MAHN_DATA
  pctfree 10
  initrans 2
  maxtrans 255;
alter table THEMES
  add foreign key (ROOM_ID)
  references ROOMS (ID) on delete cascade;

prompt Creating TRANSFERS...
create table TRANSFERS
(
  id            NUMBER generated by default as identity,
  entry_id      NUMBER not null,
  from_user_id  NUMBER not null,
  to_user_id    NUMBER not null,
  transfer_date DATE default SYSDATE
)
tablespace MAHN_DATA
  pctfree 10
  initrans 1
  maxtrans 255;
alter table TRANSFERS
  add primary key (ID)
  using index
  tablespace MAHN_DATA
  pctfree 10
  initrans 2
  maxtrans 255;
alter table TRANSFERS
  add foreign key (ENTRY_ID)
  references ENTRIES (ID);
alter table TRANSFERS
  add foreign key (FROM_USER_ID)
  references USERS (ID);
alter table TRANSFERS
  add foreign key (TO_USER_ID)
  references USERS (ID);

prompt Disabling triggers for MUSEUMS...
alter table MUSEUMS disable all triggers;
prompt Disabling triggers for ROOMS...
alter table ROOMS disable all triggers;
prompt Disabling triggers for COLLECTIONS...
alter table COLLECTIONS disable all triggers;
prompt Disabling triggers for PAYMENT_METHODS...
alter table PAYMENT_METHODS disable all triggers;
prompt Disabling triggers for USERS...
alter table USERS disable all triggers;
prompt Disabling triggers for PURCHASES...
alter table PURCHASES disable all triggers;
prompt Disabling triggers for COMMISSIONS...
alter table COMMISSIONS disable all triggers;
prompt Disabling triggers for ENTRIES...
alter table ENTRIES disable all triggers;
prompt Disabling triggers for PRICES...
alter table PRICES disable all triggers;
prompt Disabling triggers for REVIEWS...
alter table REVIEWS disable all triggers;
prompt Disabling triggers for ROOM_IMAGES...
alter table ROOM_IMAGES disable all triggers;
prompt Disabling triggers for SPECIES...
alter table SPECIES disable all triggers;
prompt Disabling triggers for THEMES...
alter table THEMES disable all triggers;
prompt Disabling triggers for TRANSFERS...
alter table TRANSFERS disable all triggers;
prompt Disabling foreign key constraints for ROOMS...
alter table ROOMS disable constraint SYS_C008598;
prompt Disabling foreign key constraints for COLLECTIONS...
alter table COLLECTIONS disable constraint SYS_C008604;
prompt Disabling foreign key constraints for PURCHASES...
alter table PURCHASES disable constraint SYS_C008637;
alter table PURCHASES disable constraint SYS_C008638;
prompt Disabling foreign key constraints for COMMISSIONS...
alter table COMMISSIONS disable constraint SYS_C008645;
alter table COMMISSIONS disable constraint SYS_C008646;
prompt Disabling foreign key constraints for ENTRIES...
alter table ENTRIES disable constraint SYS_C008656;
alter table ENTRIES disable constraint SYS_C008657;
prompt Disabling foreign key constraints for PRICES...
alter table PRICES disable constraint SYS_C008622;
prompt Disabling foreign key constraints for REVIEWS...
alter table REVIEWS disable constraint SYS_C008671;
alter table REVIEWS disable constraint SYS_C008672;
prompt Disabling foreign key constraints for ROOM_IMAGES...
alter table ROOM_IMAGES disable constraint SYS_C008677;
prompt Disabling foreign key constraints for SPECIES...
alter table SPECIES disable constraint SYS_C008609;
prompt Disabling foreign key constraints for THEMES...
alter table THEMES disable constraint SYS_C008614;
prompt Disabling foreign key constraints for TRANSFERS...
alter table TRANSFERS disable constraint SYS_C008663;
alter table TRANSFERS disable constraint SYS_C008664;
alter table TRANSFERS disable constraint SYS_C008665;
prompt Loading MUSEUMS...
prompt Table is empty
prompt Loading ROOMS...
prompt Table is empty
prompt Loading COLLECTIONS...
prompt Table is empty
prompt Loading PAYMENT_METHODS...
prompt Table is empty
prompt Loading USERS...
insert into USERS (id, name, email, password, role, phone, registration_date)
values (1001, 'Ana Rodríguez', 'ana.rodriguez@example.com', 'prueba123', 'client', '8888-9999', to_date('16-06-2025 19:24:08', 'dd-mm-yyyy hh24:mi:ss'));
insert into USERS (id, name, email, password, role, phone, registration_date)
values (2, 'John', 'jp57084@gmail.com', '1234', 'admin', '12345678', to_date('16-06-2025 02:43:20', 'dd-mm-yyyy hh24:mi:ss'));
commit;
prompt 2 records loaded
prompt Loading PURCHASES...
prompt Table is empty
prompt Loading COMMISSIONS...
prompt Table is empty
prompt Loading ENTRIES...
prompt Table is empty
prompt Loading PRICES...
prompt Table is empty
prompt Loading REVIEWS...
prompt Table is empty
prompt Loading ROOM_IMAGES...
prompt Table is empty
prompt Loading SPECIES...
prompt Table is empty
prompt Loading THEMES...
prompt Table is empty
prompt Loading TRANSFERS...
prompt Table is empty
prompt Enabling foreign key constraints for ROOMS...
alter table ROOMS enable constraint SYS_C008598;
prompt Enabling foreign key constraints for COLLECTIONS...
alter table COLLECTIONS enable constraint SYS_C008604;
prompt Enabling foreign key constraints for PURCHASES...
alter table PURCHASES enable constraint SYS_C008637;
alter table PURCHASES enable constraint SYS_C008638;
prompt Enabling foreign key constraints for COMMISSIONS...
alter table COMMISSIONS enable constraint SYS_C008645;
alter table COMMISSIONS enable constraint SYS_C008646;
prompt Enabling foreign key constraints for ENTRIES...
alter table ENTRIES enable constraint SYS_C008656;
alter table ENTRIES enable constraint SYS_C008657;
prompt Enabling foreign key constraints for PRICES...
alter table PRICES enable constraint SYS_C008622;
prompt Enabling foreign key constraints for REVIEWS...
alter table REVIEWS enable constraint SYS_C008671;
alter table REVIEWS enable constraint SYS_C008672;
prompt Enabling foreign key constraints for ROOM_IMAGES...
alter table ROOM_IMAGES enable constraint SYS_C008677;
prompt Enabling foreign key constraints for SPECIES...
alter table SPECIES enable constraint SYS_C008609;
prompt Enabling foreign key constraints for THEMES...
alter table THEMES enable constraint SYS_C008614;
prompt Enabling foreign key constraints for TRANSFERS...
alter table TRANSFERS enable constraint SYS_C008663;
alter table TRANSFERS enable constraint SYS_C008664;
alter table TRANSFERS enable constraint SYS_C008665;
prompt Enabling triggers for MUSEUMS...
alter table MUSEUMS enable all triggers;
prompt Enabling triggers for ROOMS...
alter table ROOMS enable all triggers;
prompt Enabling triggers for COLLECTIONS...
alter table COLLECTIONS enable all triggers;
prompt Enabling triggers for PAYMENT_METHODS...
alter table PAYMENT_METHODS enable all triggers;
prompt Enabling triggers for USERS...
alter table USERS enable all triggers;
prompt Enabling triggers for PURCHASES...
alter table PURCHASES enable all triggers;
prompt Enabling triggers for COMMISSIONS...
alter table COMMISSIONS enable all triggers;
prompt Enabling triggers for ENTRIES...
alter table ENTRIES enable all triggers;
prompt Enabling triggers for PRICES...
alter table PRICES enable all triggers;
prompt Enabling triggers for REVIEWS...
alter table REVIEWS enable all triggers;
prompt Enabling triggers for ROOM_IMAGES...
alter table ROOM_IMAGES enable all triggers;
prompt Enabling triggers for SPECIES...
alter table SPECIES enable all triggers;
prompt Enabling triggers for THEMES...
alter table THEMES enable all triggers;
prompt Enabling triggers for TRANSFERS...
alter table TRANSFERS enable all triggers;

set feedback on
set define on
prompt Done
